name: Deploy Gateway

on:
  push:
    branches:
      - master
#    paths:
#      - 'news/**'
#  workflow_dispatch:

jobs:

  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Install dependencies
        run: mvn clean install